### ISSUE TITLE
建议在 文档Q&A 添加 为什么无法通过邀请链接 加入 Bkebi 的 Discord 群组

### ISSUE THREAD

**Issue by AzumWatson** [Bkebi-Group/Bkebi-Group.github.io#30]
rt

是需要什么资格吗 或者 人数太多暂不开放？ 或是 每隔一段时间开放一段时间？

![image](https://user-images.githubusercontent.com/102755150/223367666-9fd36320-4b0d-444e-98e5-20a4c4e2b47b.png)

**Comment by xinyihl** [comment]
we will add it
